import time
from rich.console import Console

def move_cursor(row, column):
    print(f'\033[{row};{column}H', end='')

def logo(shade,line):
    line0 = f'[grey{shade}]                                                       [/]'
    line1 = f'[grey{shade}]╭─────────╮  ╭─╮  ╭─────────╮  ╭─────────╮  ╭─────────╮[/]'
    line2 = f'[grey{shade}]╰──────╮  │  ╰─╯  ╰─────────╯  ╰──────╮  │  │ ╭───────╯[/]'
    line3 = f'[grey{shade}]╭──────╯  │  ╭─╮  ╭───────╮    ╭──────╯  │  │ ╰───────╮[/]'
    line4 = f'[grey{shade}]│ ╭───────╯  │ │  │ ╭─────╯    │ ╭────╮  ⎨  ╰──────╮  │[/]'
    line5 = f'[grey{shade}]│ │          │ │  │ ╰───────╮  │ │    │  │  ╭──────╯  │[/]'
    line6 = f'[grey{shade}]╰─╯          ╰─╯  ╰─────────╯  ╰─╯    ╰──╯  ╰─────────╯[/]'
    logo = [line0, line1, line2, line3, line4, line5, line6]
    return logo[line]

console = Console()

console.clear()

console.print('Loading...', end='')
time.sleep(1)

speed = .05

move_cursor(8,14)
console.print(logo(15,1),)
move_cursor(1,1)
console.print('Loading...', end='')
time.sleep(speed)

move_cursor(9,14)
console.print(logo(15,2))
move_cursor(8,14)
console.print(logo(100,1))
move_cursor(1,1)
console.print('Loading...', end='')
time.sleep(speed)

move_cursor(10,14)
console.print(logo(15,3))
move_cursor(9,14)
console.print(logo(100,2))
move_cursor(8,14)
console.print(logo(70,1))
move_cursor(1,1)
console.print('Loading...', end='')
time.sleep(speed)

move_cursor(11,14)
console.print(logo(15,4))
move_cursor(10,14)
console.print(logo(100,3))
move_cursor(9,14)
console.print(logo(70,2))
move_cursor(8,14)
console.print(logo(50,1))
move_cursor(1,1)
console.print('Loading...', end='')
time.sleep(speed)

move_cursor(12,14)
console.print(logo(15,5))
move_cursor(11,14)
console.print(logo(100,4))
move_cursor(10,14)
console.print(logo(70,3))
move_cursor(9,14)
console.print(logo(50,2))
move_cursor(8,14)
console.print(logo(30,1))
move_cursor(1,1)
console.print('Loading...', end='')
time.sleep(speed)

move_cursor(13,14)
console.print(logo(15,6))
move_cursor(12,14)
console.print(logo(100,5))
move_cursor(11,14)
console.print(logo(70,4))
move_cursor(10,14)
console.print(logo(50,3))
move_cursor(9,14)
console.print(logo(30,2))
move_cursor(8,14)
console.print(logo(0,0))
move_cursor(1,1)
console.print('Loading...', end='')
time.sleep(speed)

move_cursor(13,14)
console.print(logo(100,6))
move_cursor(12,14)
console.print(logo(70,5))
move_cursor(11,14)
console.print(logo(50,4))
move_cursor(10,14)
console.print(logo(30,3))
move_cursor(9,14)
console.print(logo(0,0))
move_cursor(1,1)
console.print('Loading...', end='')
time.sleep(speed)

move_cursor(13,14)
console.print(logo(70,6))
move_cursor(12,14)
console.print(logo(50,5))
move_cursor(11,14)
console.print(logo(30,4))
move_cursor(10,14)
console.print(logo(0,0))
move_cursor(1,1)
console.print('Loading...', end='')
time.sleep(speed)

move_cursor(13,14)
console.print(logo(50,6))
move_cursor(12,14)
console.print(logo(30,5))
move_cursor(11,14)
console.print(logo(0,0))
move_cursor(1,1)
console.print('Loading...', end='')
time.sleep(speed)

move_cursor(13,14)
console.print(logo(30,6))
move_cursor(12,14)
console.print(logo(0,0))
move_cursor(1,1)
console.print('Loading...', end='')
time.sleep(speed)

move_cursor(13,14)
console.print(logo(0,0))
move_cursor(1,1)
console.print('Loading...', end='')

time.sleep(.5)

speed = .1

move_cursor(8,14)
console.print(logo(15,1))
move_cursor(9,14)
console.print(logo(15,2))
move_cursor(10,14)
console.print(logo(15,3))
move_cursor(11,14)
console.print(logo(15,4))
move_cursor(12,14)
console.print(logo(15,5))
move_cursor(13,14)
console.print(logo(15,6))
move_cursor(1,1)
console.print('Loading...', end='')
time.sleep(speed)

move_cursor(8,14)
console.print(logo(100,1))
move_cursor(9,14)
console.print(logo(100,2))
move_cursor(10,14)
console.print(logo(100,3))
move_cursor(11,14)
console.print(logo(100,4))
move_cursor(12,14)
console.print(logo(100,5))
move_cursor(13,14)
console.print(logo(100,6))
move_cursor(1,1)
console.print('Loading...', end='')
time.sleep(speed)

move_cursor(8,14)
console.print(logo(85,1))
move_cursor(9,14)
console.print(logo(85,2))
move_cursor(10,14)
console.print(logo(85,3))
move_cursor(11,14)
console.print(logo(85,4))
move_cursor(12,14)
console.print(logo(85,5))
move_cursor(13,14)
console.print(logo(85,6))
move_cursor(1,1)
console.print('Loading...', end='')
time.sleep(speed)

move_cursor(8,14)
console.print(logo(70,1))
move_cursor(9,14)
console.print(logo(70,2))
move_cursor(10,14)
console.print(logo(70,3))
move_cursor(11,14)
console.print(logo(70,4))
move_cursor(12,14)
console.print(logo(70,5))
move_cursor(13,14)
console.print(logo(70,6))
move_cursor(1,1)
console.print('Loading...', end='')

time.sleep(.25)

move_cursor(15,22)
console.print('[grey15]The Raspberry Pi Event Reporting System[/]',end='')
move_cursor(1,1)
console.print('Loading...', end='')
time.sleep(speed)

move_cursor(15,22)
console.print('[grey100]The Raspberry Pi Event Reporting System[/]',end='')
move_cursor(1,1)
console.print('Loading...', end='')
time.sleep(speed)

move_cursor(15,22)
console.print('[grey85][grey89]T[/]he [grey89]R[/]aspberry [grey89]P[/]i [grey89]E[/]vent [grey89]R[/]eporting [grey89]S[/]ystem[/]',end='')
move_cursor(1,1)
console.print('Loading...', end='')
time.sleep(speed)

move_cursor(15,22)
console.print('[grey70][grey89]T[/]he [grey89]R[/]aspberry [grey89]P[/]i [grey89]E[/]vent [grey89]R[/]eporting [grey89]S[/]ystem[/]',end='')
move_cursor(1,1)
console.print('Loading...', end='')

time.sleep(2)
console.clear()