from console import console, cursor_move

def mock_menu():
    console.clear()
    cursor_move(1,1)
    console.print('HEADER > Main Menu')
    console.print('╭──────────────────────────────────────────────────────────────────────────────╮')
    console.print('│                                                                              │')
    console.print('│                                                                              │')
    console.print('│                                                                              │')
    console.print('│                                                                              │')
    console.print('│                                                                              │')
    console.print('│                                                                              │')
    console.print('│                                                                              │')
    console.print('│                                                                              │')
    console.print('│                                                                              │')
    console.print('│                                                                              │')
    console.print('│                                                                              │')
    console.print('│                                                                              │')
    console.print('│                                                                              │')
    console.print('│                                                                              │')
    console.print('│                                                                              │')
    console.print('│                                                                              │')
    console.print('│                                                                              │')
    console.print('│                                                                              │')
    console.print('│                                                                              │')
    console.print('╰──────────────────────────────────────────────────────────────────────────────╯')
    console.print()
    console.print('Press CTRL+C to quit')
